"""Airflow DAG generator.

Renders a Python DAG file from a list of task specs. No Airflow runtime is
required to generate the file. The generated DAG is syntactically valid Python
that Airflow can pick up under ``$AIRFLOW_HOME/dags``.
"""
from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from typing import Optional


_VALID_TASK_ID = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


@dataclass
class TaskSpec:
    task_id: str
    bash_command: str
    upstream: tuple[str, ...] = ()


@dataclass
class AirflowConfig:
    """Static config for :class:`AirflowDAGGenerator`.

    Attributes:
        dag_id: DAG identifier.
        schedule: cron-style schedule string.
        owner: DAG owner.
        start_date: ISO date for the start_date kwarg.
        catchup: whether Airflow backfills.
    """
    dag_id: str = "quantforge_pipeline"
    schedule: str = "0 6 * * *"
    owner: str = "quantforge"
    start_date: str = "2025-01-01"
    catchup: bool = False


class AirflowDAGGenerator:
    """Generate a Python DAG file for an Airflow data pipeline."""

    def __init__(self, config: Optional[AirflowConfig] = None) -> None:
        self.config = config or AirflowConfig()

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------
    def render(self, tasks: list[TaskSpec]) -> str:
        """Render DAG source as a string."""
        for t in tasks:
            if not _VALID_TASK_ID.match(t.task_id):
                raise ValueError(f"invalid task_id: {t.task_id!r}")
        ids = {t.task_id for t in tasks}
        for t in tasks:
            for up in t.upstream:
                if up not in ids:
                    raise ValueError(
                        f"task {t.task_id!r} depends on unknown {up!r}"
                    )
        cfg = self.config
        lines: list[str] = []
        lines.append('"""Auto-generated by quantforge.dataeng.airflow_dags."""')
        lines.append("from datetime import datetime")
        lines.append("from airflow import DAG")
        lines.append("from airflow.operators.bash import BashOperator")
        lines.append("")
        lines.append("default_args = {")
        lines.append(f"    'owner': {cfg.owner!r},")
        lines.append(f"    'start_date': datetime.fromisoformat({cfg.start_date!r}),")
        lines.append("}")
        lines.append("")
        lines.append("dag = DAG(")
        lines.append(f"    dag_id={cfg.dag_id!r},")
        lines.append(f"    schedule={cfg.schedule!r},")
        lines.append(f"    catchup={bool(cfg.catchup)},")
        lines.append("    default_args=default_args,")
        lines.append(")")
        lines.append("")
        for t in tasks:
            lines.append(f"{t.task_id} = BashOperator(")
            lines.append(f"    task_id={t.task_id!r},")
            lines.append(f"    bash_command={t.bash_command!r},")
            lines.append("    dag=dag,")
            lines.append(")")
        lines.append("")
        for t in tasks:
            for up in t.upstream:
                lines.append(f"{up} >> {t.task_id}")
        return "\n".join(lines) + "\n"

    def write(self, tasks: list[TaskSpec], output_dir: str) -> str:
        """Render and write to ``<output_dir>/<dag_id>.py``. Returns path."""
        os.makedirs(output_dir, exist_ok=True)
        path = os.path.join(output_dir, f"{self.config.dag_id}.py")
        src = self.render(tasks)
        with open(path, "w", encoding="utf-8") as f:
            f.write(src)
        return path
