"""Lean export adapter -- Aurora StrategySpec -> Lean C# project.

Both spec variants are accepted on input:

* :class:`aurora.research.factory.spec.StrategySpec` (immutable
  factory record with ``spec_hash``, ``policy_hash``, ``universe``,
  ``rebalance``, ``strategy_class``, ``params``).
* :class:`aurora.strategies.base.StrategySpec` (GA parameter-range
  descriptor with ``name``, ``params``).

Inputs are duck-typed: anything with at least ``name`` and ``params`` is
accepted. Optional attributes used when present:

* ``strategy_class`` -- fully qualified import path (factory variant).
* ``universe`` -- list of tickers (factory variant).
* ``rebalance`` -- cadence label (factory variant).
* ``spec_hash`` -- canonical hash (factory variant). When absent, the
  exporter computes a SHA-256 over the params payload.

Translation tiers (:meth:`LeanExporter._classify_translation`):

* ``"full"`` -- known QF strategy with a complete Lean equivalent
  template (``MACross``, ``RSIMeanRev`` minimal subset).
* ``"partial"`` -- known shape (e.g. ``TSMomentum``, ``BollingerMR``)
  with a Lean skeleton + TODO blocks for the bits that need a manual
  port.
* ``"scaffold-only"`` -- unknown class. The Lean ``OnData`` body is a
  TODO and the original params dict is embedded as a comment.

R54 note: every "TODO" / "FIXME" string in this module is content
embedded into the *generated Lean C# code*, not pending Python work.
The comments tell the Lean-side operator which methods need a manual
port; no Python action is required from Aurora maintainers.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from string import Template
from typing import Any, Optional

import pandas as pd

from aurora.core.protocol_policy import ProtocolPolicy


# ---------------------------------------------------------------------------
# Public dataclasses
# ---------------------------------------------------------------------------


@dataclass
class LeanExportConfig:
    """Configuration for a Lean export run.

    Attributes:
        target_directory: Parent directory under which a project
            sub-directory ``<project_name>/`` will be created.
        project_name: Name of the project directory and the C# class
            (sanitized to a valid C# identifier).
        cash: Initial cash for the Lean ``SetCash`` call.
        benchmark: Lean benchmark symbol (default ``"SPY"``).
        resolution: Lean ``Resolution`` enum value -- ``"Daily"`` /
            ``"Hour"`` / ``"Minute"`` / ``"Tick"``.
        universe_resolution: Lean ``UniverseSettings.Resolution`` value;
            usually equal to ``resolution``.
        start_date: Lean ``SetStartDate`` date.
        end_date: Optional ``SetEndDate``; ``None`` means an open-ended
            backtest (Lean defaults to "today").
        include_costs_from_policy: When ``True`` (default), the README
            mentions the QF cost-floor pulled from
            :class:`ProtocolPolicy`. Lean's own cost model is used at
            runtime; this flag only controls README annotation.
        include_validation_marker: When ``True``, the README and
            metadata reference any ``validation_marker`` passed to
            :meth:`LeanExporter.export`. When no marker is supplied, the
            README warns that the export is research-grade only.
    """

    target_directory: Path
    project_name: str
    start_date: pd.Timestamp
    cash: float = 100_000
    benchmark: str = "SPY"
    resolution: str = "Daily"
    universe_resolution: str = "Daily"
    end_date: Optional[pd.Timestamp] = None
    include_costs_from_policy: bool = True
    include_validation_marker: bool = True


@dataclass(frozen=True)
class LeanProjectArtifact:
    """Immutable result record from :meth:`LeanExporter.export`.

    Attributes:
        project_name: Name of the project directory (matches
            ``LeanExportConfig.project_name``).
        main_cs_path: Absolute path to the generated ``Main.cs``.
        config_json_path: Absolute path to the generated ``config.json``.
        research_ipynb_path: Optional path to a research notebook (not
            generated by default; reserved for a future P3.B+ step).
        readme_path: Absolute path to ``README.md``.
        files_written: All files written by the export (so callers can
            tar them up, compute a content hash, etc.).
        policy_hash: ``ProtocolPolicy.policy_hash`` at export time.
    """

    project_name: str
    main_cs_path: Path
    config_json_path: Path
    readme_path: Path
    files_written: list[Path]
    policy_hash: str
    research_ipynb_path: Optional[Path] = None


# ---------------------------------------------------------------------------
# Strategy translation registry
# ---------------------------------------------------------------------------


# Map of Aurora strategy class short-name -> translation tier. The
# short-name is the last segment of ``strategy_class`` (e.g.
# "aurora.strategies.library.ma_cross.MACross" -> "MACross"). Tier
# is purely informational; the actual rendered logic is decided by
# :meth:`LeanExporter._render_indicator_decls` etc.
TRANSLATION_TIERS: dict[str, str] = {
    "MACross": "full",
    "RSIMeanRev": "full",
    "TSMomentum": "partial",
    "BollingerMR": "partial",
    "DonchianBreakout": "partial",
    "ATRBreakout": "partial",
    "DualMomentum": "partial",
    "VolTargetWrapper": "partial",
    "StopWrapper": "partial",
    "PairTrade": "scaffold-only",
    "OnlineLearner": "scaffold-only",
    "SeqModelStrategy": "scaffold-only",
    "PairDiscoveryEngine": "scaffold-only",
    "StatArbMeanRev": "scaffold-only",
    "Momentum": "partial",
    "MeanReversion": "partial",
}


def list_translation_tiers() -> list[tuple[str, str]]:
    """Return ``[(class_name, tier), ...]`` sorted by class name.

    Used by ``forge export lean-list`` to show operators which
    strategies have a full Lean translation vs a TODO scaffold.
    """
    return sorted(TRANSLATION_TIERS.items(), key=lambda kv: kv[0])


# ---------------------------------------------------------------------------
# LeanExporter
# ---------------------------------------------------------------------------


_TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"


def _read_template(name: str) -> Template:
    path = _TEMPLATES_DIR / name
    return Template(path.read_text(encoding="utf-8"))


def _safe_class_name(raw: str) -> str:
    """Sanitize ``raw`` to a valid C# class identifier.

    C# identifiers: letter/_ followed by letters/digits/_. Anything else
    is replaced with ``_``; if the first char is a digit a leading ``_``
    is prepended.
    """
    out = []
    for ch in raw:
        if ch.isalnum() or ch == "_":
            out.append(ch)
        else:
            out.append("_")
    s = "".join(out) or "QFExportedAlgorithm"
    if s[0].isdigit():
        s = "_" + s
    return s


def _short_class_name(strategy_class: str) -> str:
    """Return the last segment of a fully-qualified import path."""
    if "." in strategy_class:
        return strategy_class.rsplit(".", 1)[-1]
    return strategy_class


def _params_block_md(params: dict) -> str:
    """Render params as a fenced JSON block for the README."""
    if not params:
        return "_(no parameters)_"
    body = json.dumps(params, indent=2, sort_keys=True, default=str)
    return "```json\n" + body + "\n```"


def _params_comment(params: dict) -> str:
    """Render params as ``// key: value`` comment lines for Main.cs."""
    if not params:
        return "//   (no parameters)"
    lines = []
    for k in sorted(params.keys()):
        v = params[k]
        lines.append(f"//   {k}: {json.dumps(v, default=str)}")
    return "\n".join(lines)


def _coerce_universe(spec: Any) -> list[str]:
    """Best-effort recovery of a tickers list from a spec.

    Order: ``spec.universe`` -> ``spec.params['universe']`` -> ``[]``.
    """
    u = getattr(spec, "universe", None)
    if isinstance(u, list) and u:
        return [str(x) for x in u]
    p = getattr(spec, "params", None) or {}
    if isinstance(p, dict):
        u2 = p.get("universe")
        if isinstance(u2, list) and u2:
            return [str(x) for x in u2]
    return []


def _coerce_rebalance(spec: Any) -> str:
    return str(getattr(spec, "rebalance", "1d") or "1d")


def _coerce_strategy_class(spec: Any) -> str:
    """Return ``strategy_class`` if present, else fall back to ``name``.

    GA-style specs only carry ``name``; in that case the class name is
    used as both the display name and the translation key.
    """
    sc = getattr(spec, "strategy_class", None)
    if sc:
        return str(sc)
    name = getattr(spec, "name", "") or ""
    return str(name)


def _coerce_spec_hash(spec: Any) -> str:
    """Return ``spec.spec_hash`` if present, else SHA-256 over params.

    The fallback exists so a GA spec (no spec_hash) can still be
    exported with deterministic provenance. The fallback hash is
    computed from a sorted JSON payload of name + params; two GA specs
    with the same name + params therefore hash to the same value.
    """
    sh = getattr(spec, "spec_hash", None)
    if sh:
        return str(sh)
    name = getattr(spec, "name", "") or ""
    params = getattr(spec, "params", {}) or {}
    payload = json.dumps(
        {"name": str(name), "params": dict(params)},
        sort_keys=True, separators=(",", ":"), default=str,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _qf_version() -> str:
    try:
        from aurora import __version__ as v
        return str(v)
    except Exception:
        return "0.0.0+local"


def _indent_json(obj: Any, *, indent_spaces: int = 4, base_indent: int = 4) -> str:
    """JSON-encode ``obj`` indented for a nested template position.

    ``json.dumps(..., indent=4)`` always anchors at column 0; when we
    splice the result into the middle of another JSON template we need
    every line *after the first* to start at the column of the
    surrounding key. ``base_indent`` is how many spaces precede the
    surrounding key in the template, so the continuation lines line up
    cleanly.
    """
    raw = json.dumps(obj, indent=indent_spaces, sort_keys=True, default=str)
    if "\n" not in raw:
        return raw
    pad = " " * base_indent
    lines = raw.split("\n")
    return lines[0] + "\n" + "\n".join(pad + ln for ln in lines[1:])


# ---------------------------------------------------------------------------
# Exporter
# ---------------------------------------------------------------------------


class LeanExporter:
    """Export a Aurora strategy spec to a Lean (QuantConnect) project.

    Parameters:
        config: :class:`LeanExportConfig` describing the export run.
        policy: :class:`ProtocolPolicy` used to bind the export to a
            specific protocol version. The export records
            ``policy._with_hash().policy_hash`` so a Lean run can be
            tied back to the exact Aurora policy active at export
            time.

    Usage::

        exporter = LeanExporter(cfg, ProtocolPolicy.default())
        artifact = exporter.export(spec, validation_marker={...})

    Files emitted under ``cfg.target_directory / cfg.project_name``:

    * ``Main.cs`` -- the QCAlgorithm subclass.
    * ``config.json`` -- Lean project config + ``qf-export`` metadata.
    * ``README.md`` -- "DO NOT TRUST IN ISOLATION" + cross-val workflow.
    * ``qf_metadata.json`` -- full provenance record.

    The exporter never writes to ``cfg.target_directory`` itself; only
    to the project sub-directory it owns. It refuses to overwrite an
    existing project directory unless ``force=True`` is passed to
    :meth:`export`.
    """

    def __init__(self, config: LeanExportConfig, policy: ProtocolPolicy) -> None:
        self.config = config
        # Bind policy hash deterministically at construction. Tests that
        # mutate the underlying policy after construction would otherwise
        # see a stale hash; binding now mirrors the factory pattern.
        self.policy = policy._with_hash() if not policy.policy_hash else policy

    # ------------------------------------------------------------------
    # Public entry points
    # ------------------------------------------------------------------

    def export(
        self,
        spec: Any,
        *,
        validation_marker: Optional[dict] = None,
        force: bool = False,
    ) -> LeanProjectArtifact:
        """Materialize the Lean project on disk and return the artifact.

        Args:
            spec: Either a factory ``StrategySpec`` (with ``spec_hash``,
                ``universe``, ``rebalance``) or a GA ``StrategySpec``
                (just ``name`` + ``params``). Anything else with
                ``name`` and ``params`` attributes is accepted.
            validation_marker: Optional caller-supplied dict. The
                exporter writes it verbatim into ``qf_metadata.json``
                under ``"validation_marker"``. When absent and
                ``config.include_validation_marker`` is True, the
                README warns that the export is research-grade only.
            force: When ``True``, allow overwriting an existing project
                directory. When ``False`` (default), raise
                :class:`FileExistsError` if the project already exists.
        """
        project_dir = Path(self.config.target_directory) / self.config.project_name
        if project_dir.exists() and not force:
            raise FileExistsError(
                f"Lean project already exists: {project_dir}. "
                f"Pass force=True to overwrite."
            )
        project_dir.mkdir(parents=True, exist_ok=True)

        # Normalize / pre-compute everything once so renderers stay
        # pure-string and easy to test.
        ctx = self._build_context(spec, validation_marker)

        main_cs_path = project_dir / "Main.cs"
        config_json_path = project_dir / "config.json"
        readme_path = project_dir / "README.md"
        metadata_path = project_dir / "qf_metadata.json"

        main_cs_path.write_text(self._render_main_cs(ctx), encoding="utf-8")
        config_json_path.write_text(self._render_config_json(ctx), encoding="utf-8")
        readme_path.write_text(self._render_readme(ctx), encoding="utf-8")
        metadata_path.write_text(self._render_metadata(ctx), encoding="utf-8")

        files = [main_cs_path, config_json_path, readme_path, metadata_path]
        return LeanProjectArtifact(
            project_name=self.config.project_name,
            main_cs_path=main_cs_path,
            config_json_path=config_json_path,
            readme_path=readme_path,
            files_written=files,
            policy_hash=self.policy.policy_hash,
            research_ipynb_path=None,
        )

    # ------------------------------------------------------------------
    # Translation helpers
    # ------------------------------------------------------------------

    def _classify_translation(self, strategy_class: str) -> str:
        return TRANSLATION_TIERS.get(_short_class_name(strategy_class), "scaffold-only")

    def _build_context(
        self,
        spec: Any,
        validation_marker: Optional[dict],
    ) -> dict:
        """Gather everything renderers need into a single dict.

        Doing the duck-typing once here keeps every ``_render_*`` method
        a pure ``Template.substitute`` call, which is trivial to test.
        """
        cfg = self.config
        name = str(getattr(spec, "name", "") or "QFStrategy")
        strategy_class = _coerce_strategy_class(spec) or name
        short = _short_class_name(strategy_class)
        params = dict(getattr(spec, "params", {}) or {})
        universe = _coerce_universe(spec) or [cfg.benchmark]
        rebalance = _coerce_rebalance(spec)
        spec_hash = _coerce_spec_hash(spec)
        translation_tier = self._classify_translation(strategy_class)
        exported_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

        # Lean wants integer Y/M/D in SetStartDate / SetEndDate. Pandas
        # Timestamp .year/.month/.day is robust across input forms.
        start = pd.Timestamp(cfg.start_date)
        end = pd.Timestamp(cfg.end_date) if cfg.end_date is not None else None

        # Tier marker: scrape the policy for which tier this start/end
        # window covers. Informational only -- the README mentions it
        # so reviewers can sanity-check that the export is bounded to
        # a reasonable QF tier (e.g. "OOS_DEV").
        tier_marker = self._tier_marker_for_dates(start, end)

        # Validation marker: write a sentinel when the caller did not
        # provide one and the config requested embedding.
        marker_present = validation_marker is not None and bool(validation_marker)
        validation_marker_block = self._validation_marker_block(
            marker_present, validation_marker
        )

        # Lean indicator block. Scaffold-only strategies get a TODO.
        indicator_decls, indicator_init, on_data_body = self._render_lean_logic(
            short, params, universe, translation_tier
        )

        return {
            "project_name": cfg.project_name,
            "class_name": _safe_class_name(cfg.project_name),
            "strategy_name": name,
            "strategy_class": strategy_class,
            "strategy_short": short,
            "translation_tier": translation_tier,
            "spec_hash": spec_hash,
            "policy_hash": self.policy.policy_hash,
            "qf_version": _qf_version(),
            "exported_at": exported_at,
            "params": params,
            "params_comment": _params_comment(params),
            "params_block_md": _params_block_md(params),
            "universe": universe,
            "universe_csv": ", ".join(universe),
            "universe_json": json.dumps(universe, default=str),
            "rebalance": rebalance,
            "cash": int(cfg.cash) if cfg.cash == int(cfg.cash) else cfg.cash,
            "benchmark": cfg.benchmark,
            "resolution": cfg.resolution,
            "universe_resolution": cfg.universe_resolution,
            "start_year": start.year,
            "start_month": start.month,
            "start_day": start.day,
            "start_date": start.strftime("%Y-%m-%d"),
            "end_date_call": (
                f"            SetEndDate({end.year}, {end.month}, {end.day});"
                if end is not None
                else "            // SetEndDate omitted (open-ended backtest)"
            ),
            "end_date": end.strftime("%Y-%m-%d") if end is not None else "(open)",
            "tier_marker": tier_marker,
            "indicator_decls": indicator_decls,
            "indicator_init": indicator_init,
            "on_data_body": on_data_body,
            "add_securities": self._render_add_securities(universe),
            "validation_marker": validation_marker,
            "validation_marker_present": "true" if marker_present else "false",
            "validation_marker_json": json.dumps(
                validation_marker if marker_present else None, default=str,
            ),
            "validation_marker_block": validation_marker_block,
            # Lean's config.json wants a flat string->string map for
            # "parameters". JSON-encode all values so booleans/numbers
            # round-trip as their Python ``str()`` form (Lean parses
            # them at runtime via GetParameter()).
            "parameters_json": _indent_json(
                {str(k): str(v) for k, v in params.items()},
                indent_spaces=4,
            ),
        }

    def _validation_marker_block(
        self, marker_present: bool, validation_marker: Optional[dict]
    ) -> str:
        """README block describing whether the export is gated."""
        if not self.config.include_validation_marker:
            return ""
        if marker_present:
            body = json.dumps(
                validation_marker, indent=2, sort_keys=True, default=str,
            )
            return (
                "## Validation marker\n\n"
                "This export carries the following caller-supplied "
                "validation marker (recorded in `qf_metadata.json`):\n\n"
                "```json\n" + body + "\n```\n"
            )
        return (
            "## EXPORTED WITHOUT VALIDATION MARKER\n\n"
            "**Research-grade only.** No Aurora validation evidence "
            "was attached to this export. Treat the Lean project as a "
            "scratchpad; do not interpret results as confirmation of "
            "any QF promotion criterion.\n"
        )

    def _tier_marker_for_dates(
        self, start: pd.Timestamp, end: Optional[pd.Timestamp]
    ) -> str:
        """Best-effort label like ``"OOS_DEV"`` for the export window.

        Used in the Main.cs comment header so a reviewer can spot a
        backtest that accidentally straddles IS / OOS_LOCKED.
        """
        try:
            tiers = self.policy.tiers or {}
        except Exception:
            return "(unknown)"
        spans = []
        for tname, t in tiers.items():
            try:
                ts = pd.Timestamp(t.start)
                te = pd.Timestamp(t.end) if t.end else pd.Timestamp("2999-12-31")
            except Exception:
                continue
            spans.append((tname, ts, te))
        if not spans:
            return "(unknown)"
        end_eff = end if end is not None else pd.Timestamp("2999-12-31")
        hits = [n for (n, ts, te) in spans if not (end_eff < ts or start > te)]
        if not hits:
            return "(out-of-range)"
        return "+".join(hits)

    # ------------------------------------------------------------------
    # Lean code-generation
    # ------------------------------------------------------------------

    def _render_add_securities(self, universe: list[str]) -> str:
        if not universe:
            return f'            AddEquity("{self.config.benchmark}", Resolution.{self.config.resolution});'
        lines = []
        for sym in universe:
            lines.append(
                f'            AddEquity("{sym}", Resolution.{self.config.resolution});'
            )
        return "\n".join(lines)

    def _render_lean_logic(
        self,
        short: str,
        params: dict,
        universe: list[str],
        tier: str,
    ) -> tuple[str, str, str]:
        """Return ``(decls, init, on_data)`` for the Main.cs body.

        Each tuple member is already indented for placement in the
        template (the template provides the surrounding ``{ }``).
        """
        primary = universe[0] if universe else self.config.benchmark
        if short == "MACross":
            return self._lean_ma_cross(primary, params)
        if short == "Momentum" or short == "TSMomentum":
            return self._lean_momentum(primary, params)
        if short == "MeanReversion" or short == "BollingerMR":
            return self._lean_mean_reversion(primary, params)
        return self._lean_scaffold(primary, params)

    def _lean_ma_cross(self, sym: str, params: dict) -> tuple[str, str, str]:
        fast = int(params.get("fast", 20))
        slow = int(params.get("slow", 100))
        allow_short = bool(params.get("allow_short", True))
        decls = (
            "        private SimpleMovingAverage _fast;\n"
            "        private SimpleMovingAverage _slow;\n"
            f'        private const string Sym = "{sym}";'
        )
        init = (
            f"            _fast = SMA(Sym, {fast}, Resolution.{self.config.resolution});\n"
            f"            _slow = SMA(Sym, {slow}, Resolution.{self.config.resolution});"
        )
        if allow_short:
            on_data = (
                "            if (!_fast.IsReady || !_slow.IsReady) return;\n"
                "            var holdings = Portfolio[Sym].Quantity;\n"
                "            if (_fast > _slow && holdings <= 0) SetHoldings(Sym, 1);\n"
                "            else if (_fast < _slow && holdings >= 0) SetHoldings(Sym, -1);"
            )
        else:
            on_data = (
                "            if (!_fast.IsReady || !_slow.IsReady) return;\n"
                "            var holdings = Portfolio[Sym].Quantity;\n"
                "            if (_fast > _slow && holdings <= 0) SetHoldings(Sym, 1);\n"
                "            else if (_fast < _slow && holdings > 0) Liquidate(Sym);"
            )
        return decls, init, on_data

    def _lean_momentum(self, sym: str, params: dict) -> tuple[str, str, str]:
        lookback = int(params.get("lookback", params.get("window", 60)))
        decls = (
            "        private Momentum _mom;\n"
            f'        private const string Sym = "{sym}";'
        )
        init = (
            f"            _mom = MOM(Sym, {lookback}, Resolution.{self.config.resolution});"
        )
        on_data = (
            "            // TODO partial: Aurora TSMomentum has additional sizing logic.\n"
            "            //               Consult qf_metadata.json -> params and port the\n"
            "            //               vol-targeting / kelly fraction step manually.\n"
            "            if (!_mom.IsReady) return;\n"
            "            if (_mom > 0 && !Portfolio[Sym].Invested) SetHoldings(Sym, 1);\n"
            "            else if (_mom < 0 && Portfolio[Sym].Invested) Liquidate(Sym);"
        )
        return decls, init, on_data

    def _lean_mean_reversion(self, sym: str, params: dict) -> tuple[str, str, str]:
        period = int(params.get("period", params.get("window", 20)))
        k = float(params.get("k", params.get("std_mult", 2.0)))
        decls = (
            "        private BollingerBands _bb;\n"
            f'        private const string Sym = "{sym}";'
        )
        init = (
            f"            _bb = BB(Sym, {period}, {k}m, MovingAverageType.Simple, "
            f"Resolution.{self.config.resolution});"
        )
        on_data = (
            "            // TODO partial: Aurora mean-reversion variants embed a\n"
            "            //               regime filter. Inspect qf_metadata.json and\n"
            "            //               wire the regime gate before relying on this.\n"
            "            if (!_bb.IsReady) return;\n"
            "            var price = Securities[Sym].Price;\n"
            "            if (price < _bb.LowerBand && !Portfolio[Sym].Invested)\n"
            "                SetHoldings(Sym, 1);\n"
            "            else if (price > _bb.UpperBand && Portfolio[Sym].Invested)\n"
            "                Liquidate(Sym);"
        )
        return decls, init, on_data

    def _lean_scaffold(self, sym: str, params: dict) -> tuple[str, str, str]:
        # Embed params as a comment block so a manual port has the full
        # original parameter set in front of it.
        param_lines = []
        for k in sorted(params.keys()):
            v = params[k]
            param_lines.append(f"            //   {k}: {json.dumps(v, default=str)}")
        param_block = "\n".join(param_lines) if param_lines else "            //   (no parameters)"
        decls = f'        private const string Sym = "{sym}";'
        init = (
            "            // TODO scaffold-only: no Lean equivalent is registered for this\n"
            "            //                   Aurora strategy class. Port the logic\n"
            "            //                   manually before running.\n"
            "            // Original QF params:\n"
            f"{param_block}"
        )
        on_data = (
            "            // TODO scaffold-only: implement OnData body manually.\n"
            "            //                   See qf_metadata.json for spec_hash and the\n"
            "            //                   Aurora strategy_class to port from.\n"
            "            return;"
        )
        return decls, init, on_data

    # ------------------------------------------------------------------
    # Renderers
    # ------------------------------------------------------------------

    def _render_main_cs(self, ctx: dict) -> str:
        # ``Template.substitute`` (strict) raises on missing placeholders, so
        # template/context drift fails loudly at export time rather than
        # producing silently malformed C#.
        return _read_template("main.cs.template").substitute(
            params_comment=ctx["params_comment"],
            **{k: ctx[k] for k in (
                "project_name", "class_name", "strategy_name", "spec_hash",
                "policy_hash", "qf_version", "exported_at", "tier_marker",
                "universe_csv", "rebalance", "start_year", "start_month",
                "start_day", "end_date_call", "cash", "benchmark",
                "universe_resolution", "add_securities",
                "indicator_decls", "indicator_init", "on_data_body",
            )},
        )

    def _render_config_json(self, ctx: dict) -> str:
        return _read_template("config.json.template").substitute(
            **{k: ctx[k] for k in (
                "project_name", "strategy_name", "spec_hash", "policy_hash",
                "qf_version", "exported_at", "parameters_json",
                "validation_marker_present",
            )},
        )

    def _render_readme(self, ctx: dict) -> str:
        return _read_template("readme.md.template").substitute(
            params_block=ctx["params_block_md"],
            validation_marker_block=ctx["validation_marker_block"],
            **{k: ctx[k] for k in (
                "project_name", "qf_version", "strategy_name",
                "strategy_class", "universe_csv", "rebalance", "cash",
                "benchmark", "resolution", "start_date", "end_date",
                "spec_hash", "policy_hash", "exported_at",
                "translation_tier",
            )},
        )

    def _render_metadata(self, ctx: dict) -> str:
        return _read_template("qf_metadata.json.template").substitute(
            params_json=json.dumps(ctx["params"], sort_keys=True, default=str),
            **{k: ctx[k] for k in (
                "qf_version", "exported_at", "project_name", "strategy_name",
                "strategy_class", "spec_hash", "policy_hash",
                "translation_tier", "universe_json", "rebalance",
                "validation_marker_json",
            )},
        )


# ---------------------------------------------------------------------------
# Verification helpers (used by ``forge export verify``)
# ---------------------------------------------------------------------------


def verify_project(project_dir: Path) -> dict:
    """Verify the metadata stored under ``project_dir``.

    Returns a dict with keys:

    * ``ok`` (bool) -- True iff every check passed.
    * ``errors`` (list[str]) -- human-readable failure messages.
    * ``metadata`` (dict | None) -- the loaded ``qf_metadata.json``.

    Checks:

    * ``qf_metadata.json`` exists and is valid JSON.
    * The metadata declares ``policy_hash`` and ``spec_hash`` (both
      non-empty).
    * The metadata's ``policy_hash`` matches
      ``ProtocolPolicy.load()._with_hash().policy_hash`` (i.e. the
      currently active policy still matches the export).
    * The README ("DO NOT TRUST IN ISOLATION" warning) is present.

    The function never raises on a bad project; all failures are
    reported via the ``errors`` list so a CLI caller can render them.
    """
    project_dir = Path(project_dir)
    errors: list[str] = []
    metadata: Optional[dict] = None
    meta_path = project_dir / "qf_metadata.json"

    if not project_dir.exists():
        return {"ok": False, "errors": [f"project dir not found: {project_dir}"], "metadata": None}
    if not meta_path.exists():
        errors.append("qf_metadata.json missing")
        return {"ok": False, "errors": errors, "metadata": None}

    try:
        metadata = json.loads(meta_path.read_text(encoding="utf-8"))
    except Exception as e:
        errors.append(f"qf_metadata.json invalid JSON: {e}")
        return {"ok": False, "errors": errors, "metadata": None}

    for k in ("policy_hash", "spec_hash", "qf_version", "exported_at"):
        if not metadata.get(k):
            errors.append(f"qf_metadata.json missing required field {k!r}")

    declared_policy = str(metadata.get("policy_hash", ""))
    if declared_policy:
        active = ProtocolPolicy.load()
        active_hash = active._with_hash().policy_hash
        if declared_policy != active_hash:
            errors.append(
                "policy_hash mismatch: "
                f"export declares {declared_policy[:16]}..., "
                f"active policy is {active_hash[:16]}..."
            )

    readme_path = project_dir / "README.md"
    if readme_path.exists():
        try:
            readme = readme_path.read_text(encoding="utf-8")
            if "DO NOT TRUST IN ISOLATION" not in readme:
                errors.append("README.md missing 'DO NOT TRUST IN ISOLATION' warning")
        except Exception as e:
            errors.append(f"README.md unreadable: {e}")
    else:
        errors.append("README.md missing")

    return {"ok": not errors, "errors": errors, "metadata": metadata}


__all__ = [
    "LeanExportConfig",
    "LeanExporter",
    "LeanProjectArtifact",
    "TRANSLATION_TIERS",
    "list_translation_tiers",
    "verify_project",
]
