"""Generate owner-controlled CODEOWNERS, its receipt and transition manifest."""

from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path
from typing import Any

from infra.gtbi_v7_readiness.canonical import (
    canonical_bytes,
    domain_digest,
    raw_sha256,
)

ROOT = Path(__file__).resolve().parents[1]
READINESS = ROOT / "docs/readiness/gtbi-v7"
CONTRACT = ROOT / "config/gtbi/governance/codeowners_owner_controlled.json"
CODEOWNERS = ROOT / ".github/CODEOWNERS"
RECEIPT = READINESS / "g3b_codeowners_owner_receipt.json"
MANIFEST = READINESS / "transition_manifests/g3b-codeowners-owner-v1.json"
OWNER_DIRECTIVE = READINESS / "owner_simplification_directive.json"
OWNER_DECISIONS = READINESS / "owner_decisions.json"

EXPECTED_PATTERNS = (
    "/.github/workflows/",
    "/.github/CODEOWNERS",
    "/.github/rulesets/",
    "/core/execution_policy.py",
    "/core/runtime_paths.py",
    "/gtbi/",
    "/infra/github_performance/",
    "/pyproject.toml",
    "/config/gtbi/",
    "/provenance/",
    "/docs/readiness/gtbi-v7/",
    "/security/gtbi-v7/",
    "/schemas/gtbi-v7/",
    "/containers/gtbi-v7/",
    "/requirements/gtbi-v7.lock",
    "/scripts/*gtbi*",
    "/scripts/strategy_packs/",
    "/tests/*gtbi*",
    "/docs/adr/",
    "/docs/plans/gtbi*",
)


def _read_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path}: expected a JSON object")
    return payload


def _canonical_json(path: Path) -> dict[str, Any]:
    payload = _read_json(path)
    if path.read_bytes() != canonical_bytes(payload) + b"\n":
        raise ValueError(f"{path}: expected canonical JSON")
    return payload


def _repo_path(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _task_expected_result() -> str:
    with (READINESS / "task_status.csv").open(
        encoding="utf-8",
        newline="",
    ) as handle:
        rows = list(csv.DictReader(handle))
    return next(row["expected_result"] for row in rows if row["id"] == "PREV7-0203")


def validate_contract() -> dict[str, Any]:
    """Validate owner identity, plan coverage and owner-authorized boundaries."""
    contract = _canonical_json(CONTRACT)
    if contract["schema_version"] != "gtbi_v7_owner_controlled_codeowners_contract_v1":
        raise ValueError("CODEOWNERS contract schema mismatch")
    if contract["repository"] != "trading-optimizer-lab-org/aurora":
        raise ValueError("CODEOWNERS repository mismatch")
    if tuple(contract["patterns"]) != EXPECTED_PATTERNS:
        raise ValueError("CODEOWNERS path coverage mismatch")
    if len(set(contract["patterns"])) != len(EXPECTED_PATTERNS):
        raise ValueError("CODEOWNERS patterns must be unique")

    owner = contract["owner"]
    if owner != {
        "actor_id": "github-user:271768688",
        "github_login": "gomez5757",
        "repository_permission": "admin",
        "verified_at_utc": "2026-07-31T14:37:36Z",
        "verified_endpoint": (
            "repos/trading-optimizer-lab-org/aurora/"
            "collaborators/gomez5757/permission"
        ),
    }:
        raise ValueError("CODEOWNERS owner identity mismatch")
    if contract["blocking_mode"] != "routing_only_until_stage_two":
        raise ValueError("CODEOWNERS must not become blocking prematurely")
    if contract["incremental_net_spend_usd"] != 0:
        raise ValueError("CODEOWNERS contract exceeds the owner budget")

    directive = _canonical_json(OWNER_DIRECTIVE)
    decisions = _canonical_json(OWNER_DECISIONS)
    if raw_sha256(OWNER_DIRECTIVE) != contract["owner_directive_digest"]:
        raise ValueError("CODEOWNERS owner directive digest mismatch")
    if not directive["accepted"]:
        raise ValueError("owner simplification directive is not accepted")
    if directive["owner_github_login"] != owner["github_login"]:
        raise ValueError("CODEOWNERS login differs from owner directive")
    if decisions["decisions"]["audits_and_people"]["distinct_people_required"]:
        raise ValueError("owner decisions still require distinct people")
    return contract


def build_codeowners() -> bytes:
    contract = validate_contract()
    login = contract["owner"]["github_login"]
    lines = [
        "# Generated by scripts/generate_gtbi_v7_codeowners_contract.py",
        "# Owner-controlled routing only until stage-two protection is enabled.",
        *(f"{pattern} @{login}" for pattern in contract["patterns"]),
        "",
    ]
    return "\n".join(lines).encode("utf-8")


def build_receipt() -> dict[str, Any]:
    contract = validate_contract()
    codeowners_bytes = build_codeowners()
    receipt: dict[str, Any] = {
        "schema_version": "gtbi_v7_owner_controlled_codeowners_receipt_v1",
        "repository": contract["repository"],
        "task_id": "PREV7-0203",
        "owner": contract["owner"],
        "owner_directive_digest": contract["owner_directive_digest"],
        "contract_path": _repo_path(CONTRACT),
        "contract_file_sha256": raw_sha256(CONTRACT),
        "codeowners_path": _repo_path(CODEOWNERS),
        "codeowners_sha256": raw_sha256_bytes(codeowners_bytes),
        "covered_patterns": list(EXPECTED_PATTERNS),
        "blocking_mode": contract["blocking_mode"],
        "incremental_net_spend_usd": 0,
        "github_only_acceptance": True,
        "scientific_work_performed": False,
        "locked_data_accessed": False,
        "receipt_digest": "",
    }
    receipt["receipt_digest"] = domain_digest(
        "GTBI_V7_OWNER_CONTROLLED_CODEOWNERS_RECEIPT_V1",
        receipt,
        omit_top_level_fields=("receipt_digest",),
    )
    return receipt


def raw_sha256_bytes(payload: bytes) -> str:
    """Return the repository's raw SHA-256 representation for bytes."""
    return "sha256:" + hashlib.sha256(payload).hexdigest()


def build_transition_manifest(receipt: dict[str, Any]) -> dict[str, Any]:
    evidence_paths = [
        _repo_path(RECEIPT),
        _repo_path(OWNER_DIRECTIVE),
        _repo_path(OWNER_DECISIONS),
    ]
    evidence_sha256 = [raw_sha256(ROOT / path) for path in evidence_paths]
    manifest: dict[str, Any] = {
        "schema_version": "gtbi_v7_readiness_transition_manifest_v1",
        "manifest_id": "g3b-codeowners-owner-v1",
        "transaction_id": "G3B_CLOSE-1",
        "requested_at_utc": "2026-07-31T14:37:36Z",
        "actor_id": "github-user:271768688",
        "actor_role": "repository_owner",
        "expected_base_ref": "refs/heads/main",
        "expected_base_sha_mode": "runtime_default_branch_head",
        "task_actions": [
            {
                "task_id": "PREV7-0203",
                "target_status": "done",
                "evidence_paths": evidence_paths,
                "evidence_sha256": evidence_sha256,
                "terminal_reason": "owner_controlled_codeowners_verified",
                "notes": (
                    "Owner-controlled CODEOWNERS covers every protected path "
                    "listed by the plan. It routes to the verified repository "
                    "owner and remains non-blocking until stage two."
                ),
                "files_touched": evidence_paths,
                "expected_result": _task_expected_result(),
                "alternative_completion_receipt_set_digest_or_null": (
                    receipt["receipt_digest"]
                ),
            }
        ],
        "branch_actions": [],
        "gate_actions": [],
        "owner_directive_digest": raw_sha256(OWNER_DIRECTIVE),
        "manifest_digest": "",
    }
    manifest["manifest_digest"] = domain_digest(
        "GTBI_V7_READINESS_TRANSITION_MANIFEST_V1",
        manifest,
        omit_top_level_fields=("manifest_digest",),
    )
    return manifest


def main() -> int:
    CODEOWNERS.parent.mkdir(parents=True, exist_ok=True)
    CODEOWNERS.write_bytes(build_codeowners())
    receipt = build_receipt()
    RECEIPT.write_bytes(canonical_bytes(receipt) + b"\n")
    manifest = build_transition_manifest(receipt)
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_bytes(canonical_bytes(manifest) + b"\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
