"""Strategy specification (immutable proposal record) for the Research Factory.

A ``StrategySpec`` is the unit of work submitted to
:class:`~quantforge.research.factory.factory.ResearchFactory`. It pins down
*everything* needed to reproduce a candidate strategy run:

* the hypothesis text and expected edge,
* the strategy class import path and parameters,
* the asset universe and rebalance cadence,
* the protocol policy hash at generation time so a candidate created under an
  older policy is auditable,
* a deterministic ``spec_hash`` used by the factory for deduplication,
* an optional ``parent_spec_id`` so mutations / variations carry lineage.

The factory's StrategySpec deliberately does NOT inherit from the
``quantforge.strategies.base.StrategySpec`` class, which is the GA's
parameter-range descriptor. Both names co-exist in the codebase: the GA
spec describes *what shapes a parameter can take*, while the factory spec
describes *one concrete proposal*.
"""
from __future__ import annotations

import hashlib
import json
import uuid
from dataclasses import asdict, dataclass, field
from typing import Any, Optional


# Canonical fields contributing to ``spec_hash``. Anything else (the spec_id
# itself, the generator label, the parent pointer) is metadata; two specs
# whose canonical fields agree must hash to the same value so the factory's
# dedup logic is monotonic across rebuilds.
_HASH_FIELDS = (
    "name",
    "hypothesis",
    "expected_edge_bps",
    "regime_dependence",
    "failure_modes",
    "strategy_class",
    "params",
    "universe",
    "rebalance",
)


def _canonical_payload(d: dict) -> str:
    """Return a deterministic JSON payload for hashing.

    Sorted keys, no whitespace, ASCII-safe -- the exact contract used by
    :class:`quantforge.core.protocol_policy.ProtocolPolicy.compute_hash`
    so this codebase has one canonical hashing convention.
    """
    return json.dumps(
        d,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        default=str,
    )


def _compute_spec_hash(payload: dict) -> str:
    """SHA-256 of the canonical payload of ``payload``."""
    return hashlib.sha256(
        _canonical_payload(payload).encode("utf-8")
    ).hexdigest()


def _new_spec_id() -> str:
    return uuid.uuid4().hex[:16]


@dataclass(frozen=True)
class StrategySpec:
    """Immutable proposal record submitted to the Research Factory.

    Attributes:
        spec_id: unique short uuid. Generated by :meth:`make` if not provided.
        name: human-readable label (e.g. ``"Momentum 60d"``).
        hypothesis: free-form text describing the edge being claimed.
        expected_edge_bps: prior on the expected annualized edge (basis
            points). Used as a logging hint, not a gate.
        regime_dependence: list of regime tags the hypothesis claims to
            depend on (e.g. ``["high_vol", "trending"]``).
        failure_modes: list of explicit failure-mode tags so a reviewer can
            check whether the candidate failed in a known way.
        strategy_class: fully-qualified import path
            (e.g. ``"quantforge.strategies.library.ma_cross.MACross"``).
            The factory imports and instantiates this with ``params``.
        params: keyword arguments passed to ``strategy_class``.
        universe: list of tickers the strategy trades (single-asset = list
            of length 1).
        rebalance: rebalance cadence label, e.g. ``"1d"``, ``"1w"``,
            ``"1mo"``. Currently informational only.
        spec_hash: deterministic SHA-256 of the canonical fields above.
            Filled in by :meth:`make`. Two specs whose canonical fields
            agree must hash to the same value; the factory uses this for
            deduplication.
        parent_spec_id: optional link to the spec this one was mutated
            from (lineage).
        generator: free-form label tagging the producer
            (``"human"``, ``"agent:<name>"``, ``"ga"``, ...).
        policy_hash: ``ProtocolPolicy.policy_hash`` at generation time.
            Bound by the factory at submit time; generators MUST NOT
            forge this.
    """

    spec_id: str
    name: str
    hypothesis: str
    expected_edge_bps: float
    regime_dependence: list[str]
    failure_modes: list[str]
    strategy_class: str
    params: dict[str, Any]
    universe: list[str]
    rebalance: str
    spec_hash: str
    parent_spec_id: Optional[str] = None
    generator: str = "human"
    policy_hash: str = ""

    # ------------------------------------------------------------------
    # factories
    # ------------------------------------------------------------------

    @classmethod
    def make(
        cls,
        *,
        name: str,
        hypothesis: str,
        strategy_class: str,
        params: Optional[dict[str, Any]] = None,
        expected_edge_bps: float = 0.0,
        regime_dependence: Optional[list[str]] = None,
        failure_modes: Optional[list[str]] = None,
        universe: Optional[list[str]] = None,
        rebalance: str = "1d",
        parent_spec_id: Optional[str] = None,
        generator: str = "human",
        policy_hash: str = "",
        spec_id: Optional[str] = None,
    ) -> "StrategySpec":
        """Construct a spec, computing ``spec_hash`` deterministically.

        Defaults coerce list-typed fields so ``None`` never reaches the
        canonical payload (which would change the hash if a caller forgot
        to pass an empty list).
        """
        spec_id = spec_id or _new_spec_id()
        params = dict(params or {})
        regime_dependence = list(regime_dependence or [])
        failure_modes = list(failure_modes or [])
        universe = list(universe or [])
        payload = {
            "name": name,
            "hypothesis": hypothesis,
            "expected_edge_bps": float(expected_edge_bps),
            "regime_dependence": list(regime_dependence),
            "failure_modes": list(failure_modes),
            "strategy_class": strategy_class,
            "params": dict(params),
            "universe": list(universe),
            "rebalance": rebalance,
        }
        spec_hash = _compute_spec_hash(payload)
        return cls(
            spec_id=spec_id,
            name=name,
            hypothesis=hypothesis,
            expected_edge_bps=float(expected_edge_bps),
            regime_dependence=regime_dependence,
            failure_modes=failure_modes,
            strategy_class=strategy_class,
            params=params,
            universe=universe,
            rebalance=rebalance,
            spec_hash=spec_hash,
            parent_spec_id=parent_spec_id,
            generator=generator,
            policy_hash=policy_hash,
        )

    @classmethod
    def from_dict(cls, d: dict) -> "StrategySpec":
        """Inverse of :meth:`to_dict`. Re-computes ``spec_hash``.

        The on-disk form may declare a ``spec_hash``; we recompute it from
        the canonical fields and *override* the declared value so a
        tampered file cannot smuggle in a mismatched hash without the
        recomputation catching it. Verifying a declared hash is the job of
        :meth:`verify_hash`.
        """
        d = dict(d)
        return cls.make(
            spec_id=d.get("spec_id"),
            name=str(d.get("name", "")),
            hypothesis=str(d.get("hypothesis", "")),
            expected_edge_bps=float(d.get("expected_edge_bps", 0.0)),
            regime_dependence=list(d.get("regime_dependence") or []),
            failure_modes=list(d.get("failure_modes") or []),
            strategy_class=str(d.get("strategy_class", "")),
            params=dict(d.get("params") or {}),
            universe=list(d.get("universe") or []),
            rebalance=str(d.get("rebalance", "1d")),
            parent_spec_id=d.get("parent_spec_id"),
            generator=str(d.get("generator", "human")),
            policy_hash=str(d.get("policy_hash", "")),
        )

    # ------------------------------------------------------------------
    # serialization
    # ------------------------------------------------------------------

    def to_dict(self) -> dict:
        """Return a JSON / YAML-friendly dict including ``spec_hash``."""
        return asdict(self)

    # ------------------------------------------------------------------
    # validation
    # ------------------------------------------------------------------

    def validate(self) -> list[str]:
        """Return a list of human-readable validation errors.

        Empty list = spec is structurally valid. A non-empty list does
        NOT mean the underlying strategy is sound; it means the spec
        cannot be fed to the factory at all.

        Checks:
            - non-empty name and hypothesis
            - non-empty strategy_class with at least one ``.`` (qualified)
            - universe has at least one symbol
            - rebalance is a known token (currently ``"1d"``, ``"1w"``,
              ``"1mo"``, ``"1h"``, ``"5m"``, ``"15m"``)
            - expected_edge_bps is finite
            - params is a dict (never None)
        """
        errs: list[str] = []
        if not self.name or not self.name.strip():
            errs.append("name must be a non-empty string")
        if not self.hypothesis or not self.hypothesis.strip():
            errs.append("hypothesis must be a non-empty string")
        if not self.strategy_class or "." not in self.strategy_class:
            errs.append(
                "strategy_class must be a fully-qualified import path "
                "(e.g. 'pkg.module.ClassName')"
            )
        if not isinstance(self.params, dict):
            errs.append("params must be a dict")
        if not self.universe:
            errs.append("universe must contain at least one symbol")
        elif not all(isinstance(s, str) and s.strip() for s in self.universe):
            errs.append("universe entries must be non-empty strings")
        valid_rebalance = {"1d", "1w", "1mo", "1h", "5m", "15m"}
        if self.rebalance not in valid_rebalance:
            errs.append(
                f"rebalance={self.rebalance!r} not in {sorted(valid_rebalance)}"
            )
        # Edge expectation is not a gate, but it must be finite so it can
        # be recorded in JSON. NaN / inf would break the canonical payload.
        try:
            edge = float(self.expected_edge_bps)
            if edge != edge or edge in (float("inf"), float("-inf")):
                errs.append("expected_edge_bps must be a finite number")
        except (TypeError, ValueError):
            errs.append("expected_edge_bps must be a number")
        return errs

    def verify_hash(self) -> bool:
        """True iff the recomputed ``spec_hash`` matches the stored one."""
        payload = {f: getattr(self, f) for f in _HASH_FIELDS}
        return _compute_spec_hash(payload) == self.spec_hash

    # ------------------------------------------------------------------
    # convenience
    # ------------------------------------------------------------------

    def with_policy_hash(self, policy_hash: str) -> "StrategySpec":
        """Return a copy with ``policy_hash`` set to the given value.

        Used by the factory at submit time to bind the spec to the
        active :class:`~quantforge.core.protocol_policy.ProtocolPolicy`.
        Generators are forbidden from setting ``policy_hash`` themselves;
        the factory always overwrites it.
        """
        # ``replace`` would be tidy but the dataclass is frozen and we
        # already have a constructor; rebuild from the canonical fields
        # so the spec_hash stays stable. policy_hash is metadata, not
        # part of the canonical payload, so the spec_hash does not move.
        from dataclasses import replace
        return replace(self, policy_hash=policy_hash)


__all__ = [
    "StrategySpec",
]
